### ISSUE TITLE
Adding another project

### ISSUE THREAD

**Issue by mnsc** [sindrekjr/AdventOfCodeBase#2]
I tried to add an xUnit test project to the solution to get my little baby computer restrained but realized the project ended up outside the git repo since the solution file and the project file is in the same dir. I thought that I would just move the AdventOfCodeBase-project down and get on with it but then I saw that some nice new Utilities had been added to your master and moving the project would mean that I probably would break the ability to merge those and nice things in the future in a painless way.

Would you say that it would be too much hassle to move the project one level down? =D

**Comment by sindrekjr** [comment]
I'm not sure if it makes sense for this template repository to have most of its contents in a subdirectory, if I understood you correctly. But to be honest I'm not very experienced with .NET projects yet and the .sln that exists in this one is not one that I've used yet myself at all. How would the structure look with your suggestion? .sln in root and .csproj under src/?

**Comment by sindrekjr** [comment]
I've changed my mind on this and had the main project moved down one level as of https://github.com/sindrekjr/AdventOfCodeBase/commit/9ed489bb51a2201c9524522cf22bb2fb05508d54.
